# COLORES OSCUROS
COLOR_FONDO = "#1a1b28"
COLOR_TEXTO = "white"
COLOR_BOTONES_ESPECIALES = "#52c9dc"
COLOR_BOTONES = "#1e2435"
COLOR_CAJA_TEXTO = "#1a1b28"

# COLORES CLAROS
COLOR_FONDO_LIGHT = "#ffffff"
COLOR_TEXTO_LIGHT = "black"
COLOR_BOTONES_ESPECIALES_LIGHT = "#52c9dc"
COLOR_BOTONES_LIGHT = "#f2f8fc"
COLOR_CAJA_TEXTO_LIGHT = "#ffffff"

